#################################################
# Yandex Maps routes sensors
#################################################

- platform: yandex_maps
  start: zone.home
  destination: !secret yandex_map_dest_1
  name: До работы [Саша]
- platform: yandex_maps
  start: !secret yandex_map_dest_1
  destination: zone.home
  name: До дома [Саша]
- platform: yandex_maps
  start: zone.home
  destination: !secret yandex_map_dest_2
  name: До работы [Ира] [Luxoft]
- platform: yandex_maps
  start: !secret yandex_map_dest_2
  destination: zone.home
  name: До дома [Ира] [Luxoft]
- platform: yandex_maps
  start: zone.home
  destination: !secret yandex_map_dest_3
  name: До дачи
- platform: yandex_maps
  start: !secret yandex_map_dest_3
  destination: zone.home
  name: До дома [от дачи]

- platform: template
  sensors:
    ym_dom_dacha_hr:
      value_template: >
        {{ strptime(((states('sensor.do_dachi') | int * 60) | timestamp_utc),'%Y-%m-%d %H:%M:%S').strftime('%-H ч. %M мин.') }}
    ym_dacha_dom_hr:
      value_template: >
        {{ strptime(((states('sensor.do_doma_ot_dachi') | int * 60) | timestamp_utc),'%Y-%m-%d %H:%M:%S').strftime('%-H ч. %M мин.') }}