#################################################
# Miscellaneous sensors
#################################################

- platform: influxdb
  host: a0d7b954-influxdb
  port: 8086
  username: !secret influxdb_user
  password: !secret influxdb_pass
  queries:
    - name: InfluxDB Database Size
      unit_of_measurement: MB
      value_template: "{{ (value | float / 1024 /1024) | round(1) }}"
      group_function: sum
      measurement: '"monitor"."shard"'
      database: _internal
      where: "time > now() - 10s"
      field: diskBytes

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time_iso"

- platform: command_line
  name: Supervisor updates
  command: 'curl -s http://supervisor/supervisor/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version,"addons":[.data.addons[] | select(.version != .version_latest)]}'''
  value_template: "{{ value_json.addons | length }}"
  json_attributes:
    - newest_version
    - current_version
    - addons
  unit_of_measurement: pending update(s)

- platform: command_line
  name: YAML Code Lines Count
  command: find . -name '*.yaml' -not -path "./custom_components/*" -type f -print0 | xargs -0 cat | sed '/^\s*#/d;/^\s*$/d' | wc -l
  scan_interval: 14400
  unit_of_measurement: lines

- platform: command_line
  name: ERRORS in System Log [command line]
  command: grep -c -E "^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3} ERROR .*$" /config/home-assistant.log || true
  scan_interval: 3600
  unit_of_measurement: pc
- platform: command_line
  name: WARNINGS in System Log [command line]
  command: >
    grep -E "^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}\.[0-9]{3} WARNING .*$" /config/home-assistant.log |
    grep -c -v -E "^.+ We found a custom integration .+ which has not been tested by Home Assistant.+$" || true
  scan_interval: 3600
  unit_of_measurement: pc
