#################################################
# Sensors battery status
#################################################

- platform: template
  sensors:
    battery_status_158d00031c790f:
      friendly_name: "Датчик входной двери"
      value_template: >
        {{ state_attr('binary_sensor.door_window_sensor_158d00031c790f', 'battery_level') | int }}
      unit_of_measurement: '%'
      device_class: "battery"
    battery_status_158d00039cf974:
      friendly_name: "Датчик кондиционера (Детская)"
      value_template: >
        {{ state_attr('binary_sensor.door_window_sensor_158d00039cf974', 'battery_level') | int }}
      unit_of_measurement: '%'
      device_class: "battery"
    battery_status_158d0004073b67:
      friendly_name: "Датчик кондиционера (Спальня)"
      value_template: >
        {{ state_attr('binary_sensor.door_window_sensor_158d0004073b67', 'battery_level') | int }}
      unit_of_measurement: '%'
      device_class: "battery"
    battery_status_158d0003d54725:
      friendly_name: "Датчик кондиционера (Гостиная)"
      value_template: >
        {{ state_attr('binary_sensor.door_window_sensor_158d0003d54725', 'battery_level') | int }}
      unit_of_measurement: '%'
      device_class: "battery"