#################################################
# Xiaomi Power Plug sensors
#################################################

- platform: template
  sensors:
    mipowerplug01_watts:
      friendly_name_template: "switch.plug_158d00033b702e Current Consumption"
      value_template: "{{ state_attr('switch.plug_158d00033b702e', 'load_power') | float }}"
      unit_of_measurement: 'W'
    mipowerplug02_watts:
      friendly_name_template: "switch.plug_158d000391fb00 Current Consumption"
      value_template: "{{ state_attr('switch.plug_158d000391fb00', 'load_power') | float }}"
      unit_of_measurement: 'W'