#################################################
# Air Monitor sensors
#################################################
- platform: min_max
  name: Average Carbon Dioxide In Flat
  unique_id: 7d5acec8-de0e-4055-8a2e-2187a03a8fde
  type: median
  round_digits: 0
  entity_ids:
    - sensor.air_monitor_lite_afb3_carbon_dioxide
    - sensor.air_monitor_lite_cb3b_carbon_dioxide
    - sensor.air_monitor_lite_f6a7_carbon_dioxide

- platform: min_max
  name: Average pm25 In Flat
  unique_id: 5663e213-db69-4789-93c1-007e48de0516
  type: median
  round_digits: 0
  entity_ids:
    - sensor.air_monitor_lite_cb3b_pm25
    - sensor.air_monitor_lite_afb3_pm25
    - sensor.air_monitor_lite_f6a7_pm25

- platform: min_max
  name: Average pm10 In Flat
  unique_id: d65f3d47-2df7-4bcc-9a9a-456d17248a0c
  type: median
  round_digits: 0
  entity_ids:
    - sensor.air_monitor_lite_afb3_pm10
    - sensor.air_monitor_lite_cb3b_pm10
    - sensor.air_monitor_lite_f6a7_pm10