#################################################
# Core config
#################################################

homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 172.16.16.0/24
      trusted_users:
        172.16.16.0/24: 5eb99a825ace48779fad323aac28014d
  name: Home, Sweet Home...
  time_zone: !secret home_timezone
  unit_system: metric
  currency: RUB
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  packages: !include_dir_merge_named packages
  allowlist_external_dirs:
    - /config/
    - /config/www/weather_icons/
    - /config/www/cam_snapshots/

#################################################
# Features
#################################################

api:
config:
hassio:
system_health:
stream:
zeroconf:
ssdp:
sun:
map:
mobile_app:
wake_on_lan:
person:
logbook:
history:
tag:
media_source:
my:
dhcp:
image:
energy:
usb:
#wwlln:
#cloud:
#updater:

http:
  #base_url: !secret external_url
  use_x_forwarded_for: true
  trusted_proxies: 
    - 172.16.16.253
  ip_ban_enabled: true
  login_attempts_threshold: 3

logger:
  default: warn
#  logs:
#    homeassistant.components.shell_command: debug
#    custom_components.electrolux_remote: debug
#    homeassistant.components.tuya: debug
#    homeassistant.components.http.ban: warning
#    homeassistant.components.device_tracker: debug
  filters:
    zeroconf:
      - "Received invalid packet from .* at offset .* while unpacking .*"
    custom_components.gismeteo:
      - "Timeout fetching gismeteo data"
      - "Error fetching gismeteo data: Can't update weather data! Invalid server response"

system_log:
  max_entries: 50
  fire_event: true

frontend:
  themes: !include_dir_merge_named themes

lovelace: !include lovelace/lovelace.yaml

recorder:
  db_url: !secret mysql_url
  purge_keep_days: 7
  commit_interval: 60
  exclude:
    domains:
      - updater
      - automation
      - script
      - camera
      - input_datetime
      - input_number
      - input_select
    entity_globs:
      - sensor.*_zigbee
      - sensor.*_ble
      - sensor.keenetic_gateway_*
      - sensor.*_poslednee_uvedomlenie
      - sensor.*_wifi_rssi
      - sensor.gosund_sp111_*_volt
    entities:
      - sensor.time
      - sensor.date
      - sensor.date_time_iso
      - sensor.date_formatted
      - sensor.date_current_month
      - sensor.date_previous_month
      - sensor.uptime
      - sensor.moon
      - sun.sun
      - counter.syslog_errors
      - counter.syslog_warnings
      - sensor.domofon_uptime
      - sensor.ym_dacha_dom_hr
      - sensor.ym_dom_dacha_hr
      - sensor.huawei_e5372_current_connection_duration
      - sensor.huawei_e5372_rssi
      - sensor.huawei_e5372_sinr
      - sensor.energy_flat_main_voltage
      - sensor.energy_flat_main_current
    event_types:
      - call_service

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_user
  password: !secret influxdb_pass
  max_retries: 5
  default_measurement: state
  tags_attributes:
    - friendly_name
  include:
    entities: !include influxdb_conf/influxdb_include_entities.yaml
    entity_globs: !include influxdb_conf/influxdb_include_entity_globs.yaml
  component_config_glob:
    sensor.*_zigbee:
      ignore_attributes:
        - state
        - msg_received
        - last_msg

tts:
  - platform: google_translate
    language: 'ru'

discovery:
  ignore:
    - homekit

telegram_bot:
  - platform: webhooks # or "polling"
#    url: !secret tlg_webhook_proxy_url
    api_key: !secret telegram_bot_token
#    trusted_networks:
#      - !secret tlg_webhook_proxy_ip
    allowed_chat_ids:
      - !secret tlg_stall_id
      - !secret tlg_iborisochka_id
      - !secret tlg_group_flat_1
      - !secret tlg_group_system

notify:
  - name: telegram_stall
    platform: telegram
    chat_id: !secret tlg_stall_id
  - name: telegram_iborisochka
    platform: telegram
    chat_id: !secret tlg_iborisochka_id
  - name: telegram_group_flat_1
    platform: telegram
    chat_id: !secret tlg_group_flat_1
  - name: telegram_group_system
    platform: telegram
    chat_id: !secret tlg_group_system

zha:
  zigpy_config:
    ota:
      ikea_provider: true
      ikea_update_url: http://fw.test.ota.homesmart.ikea.net/feed/version_info.json

#zabbix:
#  host: home.intra
#  username: !secret zbx_user
#  password: !secret zbx_pass

start_time:

yandex_smart_home: !include entities/yandex_smart_home/yandex_smart_home.yaml

#################################################
# Inclusions
#################################################

automation: !include_dir_merge_list automations
automation gui: !include automations.yaml
script: !include_dir_merge_named scripts
script gui: !include scripts.yaml
group: !include groups.yaml
camera: !include_dir_merge_list entities/cameras
counter: !include_dir_merge_named entities/counters
device_tracker: !include_dir_merge_list entities/device_trackers
sensor: !include_dir_merge_list entities/sensors
binary_sensor: !include_dir_merge_list entities/binary_sensors
template: !include_dir_merge_list entities/templates
light: !include_dir_merge_list entities/lights
switch: !include_dir_merge_list entities/switches
media_player: !include_dir_merge_list entities/media_players
input_select: !include_dir_merge_named entities/input_select
input_number: !include_dir_merge_named entities/input_number
input_datetime: !include_dir_merge_named entities/input_datetime
input_boolean: !include_dir_merge_named entities/input_boolean
input_text: !include_dir_merge_named entities/input_text
shell_command: !include_dir_merge_named entities/shell_commands
rest_command: !include_dir_merge_named entities/rest_command
yeelight: !include entities/yeelight/yeelight.yaml
sonoff: !include entities/sonofflan/sonofflan.yaml