#################################################
# Miscellaneous binary sensors
#################################################

- platform: tod
  name: time_between_17_21
  after: '17:00'
  before: '21:00'

- platform: tod
  name: time_between_07_10
  after: '07:00'
  before: '10:00'

- platform: tod
  name: time_between_21_08
  after: '21:00'
  before: '08:00'