#################################################
# Devica Trackers
#################################################

- platform: bluetooth_le_tracker
  track_new_devices: false
  track_battery: true
  consider_home: 60