#################################################
# AC binary sensors
#################################################

- platform: template
  sensors:
    ac_nursery_status:
      device_class: power
      value_template: "{{ is_state('binary_sensor.0x158d00039cf974_contact', 'on') }}"
    ac_living_room_status:
      device_class: power
      value_template: "{{ is_state('binary_sensor.0x158d0003d54725_contact', 'on') }}"
    ac_bedroom_status:
      device_class: power
      value_template: "{{ is_state('binary_sensor.0x158d0004073b67_contact', 'on') }}"