#################################################
# Miscellaneous binary sensors
#################################################

- platform: workday
  country: RU

- platform: tod
  name: time_between_17_21
  after: '17:00'
  before: '21:00'

- platform: tod
  name: time_between_7_10
  after: '7:00'
  before: '10:00'

- platform: ping
  host: 172.16.16.206
  name: "SamsungTV-40C5100"
  count: 3
  scan_interval: 10

- platform: command_line
  name: "Mount mnt nas check"
  command: 'grep -c /mnt/nas /proc/mounts || true'
  payload_on: "1"
  payload_off: "0"