binary_sensor:
  - platform: ble_presence
    name: ${room_name} OnePlus 8T Presence
    ibeacon_uuid: "ed5e33eb-0ca3-4263-a681-a68b1045a5e6"
    device_class: "presence"
    icon: mdi:cellphone
    filters:
      - delayed_off: 10s

  - platform: ble_presence
    name: ${room_name} Amazfit GTR 4 Presence
    mac_address: C5:54:47:7D:B1:9F
    device_class: "presence"
    icon: mdi:watch
    filters:
      - delayed_off: 15s

  - platform: ble_presence
    name: ${room_name} Holy IoT Black-1 Presence
    ibeacon_uuid: "fda50693-a4e2-4fb1-afcf-c6eb07647825"
    ibeacon_major: 10011
    ibeacon_minor: 1
    device_class: "presence"
    icon: mdi:key-chain-variant
    filters:
      - delayed_off: 30s
    on_press:
      - script.execute: ble_active_scan

  - platform: ble_presence
    name: ${room_name} Holy IoT Green-1 Presence
    ibeacon_uuid: "fda50693-a4e2-4fb1-afcf-c6eb07647825"
    ibeacon_major: 10011
    ibeacon_minor: 2
    device_class: "presence"

  - platform: ble_presence
    name: ${room_name} Holy IoT White-1 Presence
    ibeacon_uuid: "fda50693-a4e2-4fb1-afcf-c6eb07647826"
    ibeacon_major: 10011
    ibeacon_minor: 3
    device_class: "presence"
    icon: mdi:car-key
    filters:
      - delayed_off: 30s
    on_press:
      - script.execute: ble_active_scan

  - platform: ble_presence
    name: ${room_name} Nut Gray-1 Presence
    mac_address: F8:3F:C3:FC:F8:A9
    device_class: "presence"
    icon: mdi:tag-outline