wifi:
  reboot_timeout: 15min
#  fast_connect: true
  output_power: 20dB
  power_save_mode: none
  networks:
    - ssid: !secret wifi_ch_ssid
      password: !secret wifi_ch_password
      priority: 1
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      priority: 2
  ap:
    ssid: ${board_name}
    password: !secret wifi_fallback_ap_pass