wifi:
  reboot_timeout: 15min
#  fast_connect: true
  output_power: 20dB
  power_save_mode: none
  networks:
    - ssid: !secret wifi_ch_mesh_ssid
      password: !secret wifi_ch_mesh_password
      priority: 10
    - ssid: !secret wifi_mesh_ssid
      password: !secret wifi_mesh_password
      priority: 5
  ap:
    ssid: ${board_name}
    password: !secret wifi_fallback_ap_pass