#################################################
# Media automatization
#################################################

- alias: "PowerOff all media when nobody at home"
  id: 0e2312c7-3cab-413a-aefb-20ff5802c718
  initial_state: true
  trigger:
    platform: state
    entity_id: group.family_persons
    to: "not_home"
    for:
      minutes: 5
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: group.all_tv
        state: "on"
      - condition: state
        entity_id: group.all_chromecasts
        state: "on"
      - condition: state
        entity_id: media_player.yandex_station_lite_detskaia
        state: "playing"
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.all_tv
    - service: media_player.media_stop
      data:
        entity_id:
          - group.all_chromecasts
          - group.all_yandex_stations

- alias: "Wakeup Radio - Childrens"
  id: 75d1f4fc-c40b-433a-b6bc-ed480b53365e
  trigger:
    platform: time
    at: input_datetime.wakeup_radio_in_nursery
  condition:
    condition: state
    entity_id: binary_sensor.workday_sensor
    state: "on"
  action:
    - service: media_player.volume_set
      entity_id: media_player.yandex_station_lite_detskaia
      data:
        volume_level: "0.0"
    - delay: "00:00:01"
    - service: yandex_station.send_command
      data:
        entity_id: media_player.yandex_station_lite_detskaia
        command: sendText
        text: Включи детское радио
    - alias: Increase volume by 10%
      repeat:
        while:
          - condition: template
            value_template: "{{ repeat.index <= 5 }}"
        sequence:
          - delay: "00:03:00"
          - service: media_player.volume_set
            entity_id: media_player.yandex_station_lite_detskaia
            data_template:
              volume_level: >
                {% set level = (state_attr('media_player.yandex_station_lite_detskaia', 'volume_level') | float) + (0.1 | float) %}
                {% if level < 1 %} {{ level }}
                {% else %} 1
                {% endif %}
    - service: yandex_station.send_command
      data:
        entity_id: media_player.yandex_station_lite_detskaia
        command: sendText
        text: Повтори за мной 'Доброе утро, пора вставать!'