#################################################
# System
#################################################

#- alias: "Restart FFmpeg process"
#  initial_state: false
#  trigger:
#    platform: state
#    entity_id: binary_sensor.dvizhenie_v_detskoi
#    to: 'unavailable'
#  action:
#    - service: ffmpeg.restart
#    - service: notify.telegram_stall
#      data:
#        message: "_INFO:_ Перезапущен процесс ffmpeg"
#    - delay:
#        seconds: 10

#- alias: "Temporary - Dismiss Discovery Notifications"
#  initial_state: true
#  trigger:
#    - platform: event
#      event_type: config_entry_discovered
#  action:
#    - service: persistent_notification.dismiss
#      data:
#        notification_id: config_entry_discovery

- alias: "HA: Mount NFS Share from NAS02 [/nmt/nas]"
  id: eb3ef8ea-e19a-4b1e-b7ff-482089a346b5
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: switch.turn_on
      entity_id: switch.mount_mnt_nas

- alias: "HA: Create Weekly Backup"
  id: 03e8310d-cabf-4988-896b-f4a9a3f2f723
  initial_state: true
  trigger:
    - platform: time
      at: "02:45:00"
  condition:
    - condition: time
      weekday:
        - thu
  action:
    - service: auto_backup.snapshot_full
      data_template:
        name: >
          ha_weekly_backup_{{ now().strftime('%Y%m%d') }}
        keep_days: 13
        backup_path: "/mnt/nas/ha_backups/weekly"

- alias: "HA: Create Daily Backup"
  id: acac055e-ea1e-41cd-9f46-62e7a8c006aa
  initial_state: true
  trigger:
    - platform: time
      at: "01:00:00"
  condition:
    - condition: state
      entity_id: binary_sensor.mount_mnt_nas_check
      state: "on"
  action:
    - service: auto_backup.snapshot_full
      data:
        name: "ha_daily_backup_{{ now().strftime('%Y%m%d') }}"
        keep_days: 7
        backup_path: "/mnt/nas/ha_backups/daily"

- alias: "HASS: ERRORs in System Log - Counter"
  id: 3b8230a5-49d5-437b-8bd9-d3f72f95425f
  trigger:
    platform: event
    event_type: system_log_event
    event_data:
      level: ERROR
  mode: parallel
  max: 50
  action:
    - service: counter.increment
      entity_id: counter.syslog_errors

- alias: "HASS: WARNINGs in System Log - Counter"
  id: acdf3489-b611-445c-bd24-2efc9c431124
  trigger:
    platform: event
    event_type: system_log_event
    event_data:
      level: WARNING
  mode: parallel
  max: 50
  action:
    - service: counter.increment
      entity_id: counter.syslog_warnings

- alias: "HASS: Create Group of Battery Devices"
  id: 823d8378-6723-4e71-93ce-29c59946347a
  trigger:
    - platform: homeassistant
      event: start
    - platform: time_pattern
      hours: "/2"
  action:
    - service: group.set
      data_template:
        object_id: battery_devices
        entities: >-
          {%- 
            for state in states.sensor 
              if is_state_attr(state.entity_id, 'device_class', 'battery') and
              (state.entity_id.endswith("_battery") or state.entity_id.endswith("_power"))
          %}
          {{ state.entity_id }}{%- if not loop.last -%}, {%- endif -%}
          {%- endfor %}

#- alias: "Mirror Notifications from Android's to Telegram"
#  trigger:
#    - platform: state
#      entity_id:
#        - sensor.kb2003_poslednee_uvedomlenie
#        - sensor.mi_8_poslednee_uvedomlenie
#  action:
#    - service: notify.telegram_stall
#      data:
#        message: |
#          {{ trigger.to_state.attributes.package }}
#          {{ trigger.to_state.state }}