#################################################
# Notifications
#################################################

- alias: "Home Presence Alert"
  id: 12b0184c-bb8b-436a-887a-733d0ddac126
  initial_state: true
  mode: parallel
  trigger:
    platform: state
    entity_id: person.alexander, person.irina, person.galina, person.tatiana, person.olga
  condition:
    condition: and
    conditions:
      #      - condition: template
      #        value_template: "{{ states('sensor.uptime') != '0.0' }}"
      - condition: template
        value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
  action:
    - service: notify.telegram_group_flat_1
      data_template:
        message: >
          {{ trigger.to_state.attributes.friendly_name }}
          {% if trigger.to_state.state == 'home' %}дома!
          {% elif trigger.to_state.state == 'Дача' %}на даче!
          {% else %}скорее всего вне дома.
          {% endif %}

- alias: Entrance Door - Opened
  id: 067c832a-9626-4f61-8d19-444d6156e889
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d00031c790f_contact
    from: "off"
    to: "on"
  action:
    service: notify.telegram_group_flat_1
    data:
      message: Открыта входная дверь!

- alias: Entrance Door - Closed
  id: c6df423a-a1ec-41fb-b600-3874ffef758b
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d00031c790f_contact
    from: "on"
    to: "off"
  action:
    service: notify.telegram_group_flat_1
    data:
      message: Входная дверь закрыта.

- alias: "Torrent Completed [notify to stall]"
  id: fe45c917-f489-4c38-a3a1-c66e5fedb07f
  initial_state: true
  trigger:
    platform: event
    event_type: transmission_downloaded_torrent
  action:
    service: notify.telegram_stall
    data_template:
      message: "Загрузка torrent-файла завершена"

- alias: "Полнолуние [notify to stall]"
  id: d698bdcc-4ce9-4954-a118-8a1f29cf327e
  initial_state: true
  trigger:
    platform: state
    entity_id: sensor.moon
    to: "full_moon"
  action:
    service: notify.telegram_stall
    data_template:
      message: "Сегодня полнолуние!"

- alias: Gas Alert
  id: 0ca74008-65a2-4ed1-b860-e27e57b216f2
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.0x158d000413b210_gas
    from: "off"
    to: "on"
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tlg_group_flat_1
        title: "*Внимание!*"
        message: |
          Сработал датчик *газа* на кухне.
          Откройте окна и перекройте подачу газа (за холодильником).
        inline_keyboard:
          - 'Отключить датчик:/poweroff_gas_sensor'

- alias: Gas Alert - Telegram control - poweroff_gas_sensor
  id: 3254a184-a04f-4b31-bbe9-1a00e403f134
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/poweroff_gas_sensor'
  action:
    - service: switch.turn_off
      entity_id: switch.mi_smartplugwifi_02
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Команда отправлена'
    - service: telegram_bot.edit_message
      data:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
        title: "*Внимание!*"
        message: |
          Сработал датчик *газа* на кухне.
          Датчик *газа* отклчюен!

- alias: Gas Alert - Sensor Powered Off More Than 30 Min
  id: 3e69fa5f-34f2-4e5e-86e2-467aad2420b6
  trigger:
    platform: state
    entity_id: switch.mi_smartplugwifi_02
    to: 'off'
    for: "00:30:00"
  action:
    - service: telegram_bot.send_message
      data:
        target: !secret tlg_group_flat_1
        title: "*Внимание!*"
        message: |
          Питание датчика *газа* отключено более 30 минут!
        inline_keyboard:
          - 'Включить датчик:/poweron_gas_sensor'

- alias: Gas Alert - Telegram control - poweroff_gas_sensor
  id: 50892fe7-741c-4b4d-a71c-a498be52d6b7
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/poweron_gas_sensor'
  action:
    - service: switch.turn_on
      entity_id: switch.mi_smartplugwifi_02
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Команда отправлена'
    - service: telegram_bot.edit_message
      data:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
        title: "*Внимание!*"
        message: |
          Питание датчика *газа* отключено более 30 минут!
          Датчик *газа* включен!

- alias: Boiler - Low Temperature Alert
  id: fe98880b-2fcd-4b6f-9ded-adc174b9b958
  trigger:
    - platform: numeric_state
      entity_id: sensor.boiler_water_temp
      below: 50
    - platform: numeric_state
      entity_id: sensor.boiler_water_temp
      below: 40
    - platform: numeric_state
      entity_id: sensor.boiler_water_temp
      below: 30
  condition:
    condition: template
    value_template: "{{ (trigger.to_state.state | int) != 0 }}"
  action:
    - service: notify.telegram_group_flat_1
      data_template:
        title: "*Внимание!*"
        message: |
          Температура воды в бойлере *{{ trigger.to_state.state }}*°C