#################################################
# Media automatization
#################################################

- alias: "PowerOff all media when nobody at home"
  id: 0e2312c7-3cab-413a-aefb-20ff5802c718
  initial_state: true
  trigger:
    platform: state
    entity_id: group.family_persons
    to: "not_home"
    for:
      minutes: 5
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: group.all_tv
        state: "on"
      - condition: state
        entity_id: group.all_chromecasts
        state: "on"
      - condition: state
        entity_id:
          - media_player.yandex_station_lite_detskaia
          - media_player.yandex_station_mini2_gostinaia
          - media_player.yandex_station_mini2_spalnia
          - media_player.yandex_station_lite_prikhozhaya
        state: "playing"
      - condition: state
        entity_id: group.all_xbox
        state: "on"
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.all_tv
    - service: media_player.media_stop
      data:
        entity_id:
          - group.all_chromecasts
          - group.all_yandex_stations
          - group.all_xbox

- alias: "Wakeup Radio - Childrens"
  id: 75d1f4fc-c40b-433a-b6bc-ed480b53365e
  trigger:
    platform: time
    at: input_datetime.wakeup_radio_in_nursery
  condition:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: "on"
    - condition: state
      entity_id: calendar.semia_alexander_borsiov_school_vacation_egor
      state: "off"
  action:
    - service: media_player.volume_mute
      target:
        entity_id: media_player.yandex_station_lite_detskaia
      data:
        is_volume_muted: "true"
    - delay: "00:00:01"
    - service: yandex_station.send_command
      data:
        entity_id: media_player.yandex_station_lite_detskaia
        command: sendText
        text: Включи детское радио
    - delay: "00:00:10"
    - service: media_player.volume_set
      target:
        entity_id: media_player.yandex_station_lite_detskaia
      data:
        volume_level: "0.1"
    - alias: Volume Up 4 times
      repeat:
        while:
          - condition: template
            value_template: "{{ repeat.index <= 4 }}"
        sequence:
          - delay: "00:03:00"
          - service: media_player.volume_up
            target:
              entity_id: media_player.yandex_station_lite_detskaia
    - service: yandex_station.send_command
      data:
        entity_id: media_player.yandex_station_lite_detskaia
        command: sendText
        text: Повтори за мной 'Доброе утро дети, пора вставать!'