#################################################
# Thermo & Climate Automations
#################################################

# Детская #######################################
- alias: Termo alert [Nursery]
  trigger:
    - platform: template
      value_template: "{{ (states('sensor.0x158d0003931aec_temperature') | float) < 22 }}"
      for:
        minutes: 5
    - platform: template
      value_template: "{{ (states('sensor.0x158d0003931aec_temperature') | float) > 25 }}"
      for:
        minutes: 5
  action:
    - service: notify.telegram_stall
      data_template:
        message: >-
          В *Детской*
          {% if (trigger.to_state.state | float) > 23 -%} жарко,
          {% elif (trigger.to_state.state | float) < 23 -%} холодно,
          {% endif -%} температура: *{{ trigger.to_state.state }}°C*

# Гостиная ######################################
- alias: Termo alert [Living Room]
  trigger:
    - platform: template
      value_template: "{{ (states('sensor.0x158d0003230618_temperature') | float) < 22 }}"
      for:
        minutes: 5
    - platform: template
      value_template: "{{ (states('sensor.0x158d0003230618_temperature') | float) > 25 }}"
      for:
        minutes: 5
  action:
    - service: notify.telegram_stall
      data_template:
        message: >-
          В *Гостиной*
          {% if (trigger.to_state.state | float) > 23 -%} жарко,
          {% elif (trigger.to_state.state | float) < 23 -%} холодно,
          {% endif -%} температура: *{{ trigger.to_state.state }}°C*

# Спальня #######################################
- alias: Termo alert [Bedroom]
  trigger:
    - platform: template
      value_template: "{{ (states('sensor.0x158d0003931b0e_temperature') | float) < 21 }}"
      for:
        minutes: 5
    - platform: template
      value_template: "{{ (states('sensor.0x158d0003931b0e_temperature') | float) > 24.5 }}"
      for:
        minutes: 5
  action:
    - service: notify.telegram_stall
      data_template:
        message: >-
          В *Спальне*
          {% if (trigger.to_state.state | float) > 23 -%} жарко,
          {% elif (trigger.to_state.state | float) < 23 -%} холодно,
          {% endif -%} температура: *{{ trigger.to_state.state }}°C*

# Оповещения о долгой работе кондиционеров ######
- alias: AC - long running [8h]
  initial_state: true
  trigger:
    platform: state
    entity_id:
      - binary_sensor.0x158d00039cf974_contact
      - binary_sensor.0x158d0003d54725_contact
      - binary_sensor.0x158d0004073b67_contact
    from: 'off'
    to: 'on'
    for:
      hours: 8
  action:
    service: notify.telegram_stall
    data_template:
      message: >
        Внимание, *{{ trigger.to_state.attributes.friendly_name }}* работает больше 8 часов.

- alias: AC - long running [16h]
  initial_state: true
  trigger:
    platform: state
    entity_id:
      - binary_sensor.0x158d00039cf974_contact
      - binary_sensor.0x158d0003d54725_contact
      - binary_sensor.0x158d0004073b67_contact
    from: 'off'
    to: 'on'
    for:
      hours: 16
  action:
    service: notify.telegram_stall
    data_template:
      message: >
        Внимание, *{{ trigger.to_state.attributes.friendly_name }}* работает больше *16* часов.

- alias: AC - long running [24h]
  initial_state: true
  trigger:
    platform: state
    entity_id:
      - binary_sensor.0x158d00039cf974_contact
      - binary_sensor.0x158d0003d54725_contact
      - binary_sensor.0x158d0004073b67_contact
    from: 'off'
    to: 'on'
    for:
      hours: 24
  action:
    service: notify.telegram_stall
    data_template:
      message: >
        Внимание, *{{ trigger.to_state.attributes.friendly_name }}* работает больше *24* часов.