#################################################
# Devica Trackers
#################################################

#- platform: keenetic_ndms2
#  host: 172.16.16.254
#  username: !secret keen_user
#  password: !secret keen_passwd
#  interval_seconds: 30
#  new_device_defaults:
#    track_new_devices: true
#- platform: nmap_tracker
#  interval_seconds: 15
#  new_device_defaults:
#    track_new_devices: true
#  hosts: 172.16.16.101-200
#  home_interval: 5
#  scan_options: " -sP --host-timeout 1s "
#- platform: google_maps
#  interval_seconds: 60
#  username: !secret google_maps_username
#- platform: luci
#  host: 192.168.10.1
#  username: !secret chouse_gw01_user
#  password: !secret chouse_gw01_pass

- platform: bluetooth_le_tracker
  track_new_devices: false
  track_battery: true
  consider_home: 60