#################################################
# Light, Lamp, etc...
#################################################

- platform: switch
  name: Детская - подсветка на окне
  entity_id: switch.blitzwolf_shp15_01_switch

- platform: switch
  name: Гостиная - подсветка на окне
  entity_id: switch.tz3000_g5xawfcq_ts0121_switch