#################################################
# Light, Lamp, etc...
#################################################

- platform: switch
  name: Детская - подсветка на окне
  entity_id: switch.0x158d00033b702e_switch

- platform: switch
  name: Гостиная - подсветка на окне
  entity_id: switch.0x158d000391fb00_switch